chore(15-matrices): remove failing step and unnecessary sleep

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -28,15 +28,15 @@ jobs:
         uses: actions/setup-node@v4
         with: 
           node-version: ${{ matrix.node-version }}
-      - name: Fail if experimental
-        if: ${{ matrix.tag == 'experimental' }}
-        run: |
-          echo "This is an experimental NodeJS version"
-          exit 1
+    #   - name: Fail if experimental
+    #     if: ${{ matrix.tag == 'experimental' }}
+    #     run: |
+    #       echo "This is an experimental NodeJS version"
+    #       exit 1
       - name: Perform some tests
         run: |
           echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
-          sleep 10
+        #   sleep 10
       - name: Upload test results
         run: echo "Uploading test results"
   include-example:
